name: Checks
on: [push, pull_request]

jobs:
  build:
    environment: CI 
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install pylint
    - run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')